### ISSUE TITLE
SRX - "show security monitoring" parser

### ISSUE THREAD

**Issue by mziegler8888** [Juniper/open-nti#170]
Hi All,

anyone working on a "show security monitoring" parser for SRX devices? Would be nice to also see CPU, memory and flows/sessions on a per FPC/PIC basis in the dashboard.

Thanks,

Martin

show security monitoring
node0:
--------------------------------------------------------------------------
                  Flow session   Flow session     CP session     CP session
FPC PIC CPU Mem        current        maximum        current        maximum
  0   0   0  13              0              0              0              0
  0   1   0   6             96        6291456            101        7549747
  0   2   0   6             89        6291456             89        7549747
  0   3   0   6             99        6291456             99        7549747
Total Sessions:            284       18874368            289       22649241

node1:
--------------------------------------------------------------------------
                  Flow session   Flow session     CP session     CP session
FPC PIC CPU Mem        current        maximum        current        maximum
  0   0   0  13              0              0              0              0
  0   1   0   6             77        6291456             79        7549747
  0   2   0   6             70        6291456             70        7549747
  0   3   0   6             72        6291456             75        7549747
Total Sessions:            219       18874368            224       22649241

**Comment by 3fr61n** [comment]
Hi

Could you please put the output command in xml?

Thanks

**Comment by mziegler8888** [comment]
Sure...

`<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <multi-routing-engine-results>

        <multi-routing-engine-item>

            <re-name>node0</re-name>

            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>0</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>13</spu-memory-utilization>
                    <spu-current-flow-session>0</spu-current-flow-session>
                    <spu-max-flow-session>0</spu-max-flow-session>
                    <spu-current-cp-session>0</spu-current-cp-session>
                    <spu-max-cp-session>0</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>1</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>77</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>89</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>2</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>73</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>73</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>3</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>75</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>75</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>Total Sessions:</fpc-number>
                    <pic-number></pic-number>
                    <spu-cpu-utilization></spu-cpu-utilization>
                    <spu-memory-utilization></spu-memory-utilization>
                    <spu-current-flow-session>225</spu-current-flow-session>
                    <spu-max-flow-session>18874368</spu-max-flow-session>
                    <spu-current-cp-session>237</spu-current-cp-session>
                    <spu-max-cp-session>22649241</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
        </multi-routing-engine-item>

        <multi-routing-engine-item>

            <re-name>node1</re-name>

            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>0</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>13</spu-memory-utilization>
                    <spu-current-flow-session>0</spu-current-flow-session>
                    <spu-max-flow-session>0</spu-max-flow-session>
                    <spu-current-cp-session>0</spu-current-cp-session>
                    <spu-max-cp-session>0</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>1</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>46</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>46</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>2</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>34</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>34</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>3</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>47</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>47</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>Total Sessions:</fpc-number>
                    <pic-number></pic-number>
                    <spu-cpu-utilization></spu-cpu-utilization>
                    <spu-memory-utilization></spu-memory-utilization>
                    <spu-current-flow-session>127</spu-current-flow-session>
                    <spu-max-flow-session>18874368</spu-max-flow-session>
                    <spu-current-cp-session>127</spu-current-cp-session>
                    <spu-max-cp-session>22649241</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
        </multi-routing-engine-item>

    </multi-routing-engine-results>
    <cli>
        <banner>{primary:node0}</banner>
    </cli>
</rpc-reply>
`

**Comment by 3fr61n** [comment]
Question, 

It is possible to have the same command per node?  like 'show security monitoring node0' and 'show security monitoring node1' ?

Regards

**Comment by mziegler8888** [comment]
Yes, it's possible.

**Comment by 3fr61n** [comment]
I don't have any lab to test it....  

Could you please do it for me?  or if I can have access to your setup.

Regards

```
parser:
    regex-command: show\s+security\s+monitoring\s+\|\s+display\s+xml
    matches:
    -
        type: multi-value
        method: xpath
        xpath: //*[local-name() = 'multi-routing-engine-item']/*[local-name() = 'performance-summary-information']/*[local-name() = 'performance-summary-statistics']
        loop:
            node: ../../*[local-name() = 're-name']
            fpc: ./*[local-name() = 'fpc-number']
            pic: ./*[local-name() = 'pic-number']
            sub-matches:
            -
                xpath: ./*[local-name() = 'spu-cpu-utilization']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-cpu-utilization
            -
                xpath: ./*[local-name() = 'spu-memory-utilization']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-memory-utilization
            -
                xpath: ./*[local-name() = 'spu-current-flow-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-current-flow-session
            -
                xpath: ./*[local-name() = 'spu-max-flow-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-max-flow-session
            -
                xpath: ./*[local-name() = 'spu-current-cp-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-current-cp-session
            -
                xpath: ./*[local-name() = 'spu-max-cp-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-max-cp-session

```
