### ISSUE TITLE
Unable to see any Open-nti UI

### ISSUE THREAD

**Issue by gaacad** [Juniper/open-nti#210]
Installed opennti as per instructions given:
```
git clone https://github.com/Juniper/open-nti.git
cd open-nti
sudo make start
```
Howver, we don't see any UI running on port 8080 as shown in the tutorial video at:  
https://junipernetworks.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=7a8d593a-2736-4165-b559-973736644cef&vid=7A3A554B-8F42-4B50-84DB-DC6475B11876

Grafana and influxdb ports are working fine.  What do we need to do to get the UI working ?

**Comment by 3fr61n** [comment]
Hi @gaacad 

The UI is grafana, so it does not matter if it's mapped to 8080 or 80 port, at the end it will be forwarded to 3000 port (grafana default).

I you want to have the grafana mapped to 8080 port the easiest way is to edit the opennti.params file
https://github.com/Juniper/open-nti/blob/master/open-nti.params#L47, and change the variable LOCAL_PORT_GRAFANA to 8080, at the end this value will be used in the container as follow

```
opennti:
  image: $MAIN_IMAGE_NAME:$IMAGE_TAG
  container_name: $MAIN_CONTAINER_NAME
# Uncomment environment to allow anonymous grafana access
# and disable user sign up
#  environment:
#   - "GF_USERS_ALLOW_SIGN_UP=false"
#   - "GF_AUTH_ANONYMOUS_ENABLED=true"
  volumes:
   - ./$LOCAL_DIR_DASHBOARD:/src/dashboards
   - ./$LOCAL_DIR_DATA:/opt/open-nti/data
   - /etc/localtime:/etc/localtime
  ports:
   - "$LOCAL_PORT_STATSD:8125/udp"
   - "$LOCAL_PORT_NGINX:80"
   - "$LOCAL_PORT_GRAFANA:3000" <<<<<
   - "$LOCAL_PORT_INFLUXDB:8083"
   - "$LOCAL_PORT_INFLUXDB_API:8086"
```

Regards
