### ISSUE TITLE
InfluxDB Tags

### ISSUE THREAD

**Issue by steiler** [Juniper/open-nti#84]
Is there a way to add InfluxDB Tags to datapoints from the parser yaml?
Besides the existing device, key, ... tags I'd like to add more tags to datapoints.

Found this: (show-route-summary.parser.yaml)

```
    loop:
        key: ./table-name
        sub-matches:
        -
            xpath: ./destination-count
            variable-name:  $host.route-table.summary.$key.destinations
            tags:
            -
                table: $key
                test: delete_me
        -
```

But unfortunately these tags don't appear in the InfluxDB.
Is there a way to add InfluxDB tags?
